"""initial schema

Revision ID: 409a6dd61e20
Revises: 
Create Date: 2026-02-20 00:21:47.209195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '409a6dd61e20'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('discogs', 'ebay', 'musicbrainz', 'spotify', name='provider_enum'), nullable=False),
    sa.Column('external_id', sa.String(length=120), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('condition', sa.String(length=30), nullable=True),
    sa.Column('seller', sa.String(length=120), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('status', sa.Enum('active', 'ended', 'unknown', name='listing_status_enum'), nullable=False),
    sa.Column('discogs_release_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.CheckConstraint('price >= 0', name='ck_listings_price_nonnegative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'external_id', name='uq_listing_provider_external')
    )
    op.create_index(op.f('ix_listings_discogs_release_id'), 'listings', ['discogs_release_id'], unique=False)
    op.create_index('ix_listings_provider_status_last_seen', 'listings', ['provider', 'status', 'last_seen_at'], unique=False)
    op.create_table('provider_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.Enum('discogs', 'ebay', 'musicbrainz', 'spotify', name='provider_enum'), nullable=False),
    sa.Column('endpoint', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_provider_requests_provider_created_at', 'provider_requests', ['provider', 'created_at'], unique=False)
    op.create_index('ix_provider_requests_status_code', 'provider_requests', ['status_code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('price_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('price >= 0', name='ck_price_snapshots_price_nonnegative'),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_snapshots_listing_recorded_at', 'price_snapshots', ['listing_id', 'recorded_at'], unique=False)
    op.create_table('watch_releases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('discogs_release_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('artist', sa.String(length=200), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('min_condition', sa.String(length=30), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'discogs_release_id', name='uq_watch_release_user_release')
    )
    op.create_index('ix_watch_releases_user_active', 'watch_releases', ['user_id', 'is_active'], unique=False)
    op.create_table('watch_search_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('query', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('poll_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_watch_search_rules_query_gin', 'watch_search_rules', ['query'], unique=False, postgresql_using='gin')
    op.create_index('ix_watch_search_rules_user_active', 'watch_search_rules', ['user_id', 'is_active'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('RULE_CREATED', 'RULE_UPDATED', 'RULE_DISABLED', 'RULE_ENABLED', 'WATCH_RELEASE_CREATED', 'WATCH_RELEASE_UPDATED', 'WATCH_RELEASE_DISABLED', 'WATCH_RELEASE_ENABLED', 'LISTING_FIRST_SEEN', 'LISTING_PRICE_DROP', 'LISTING_PRICE_RISE', 'LISTING_ENDED', 'NEW_MATCH', name='event_type_enum'), nullable=False),
    sa.Column('watch_release_id', sa.UUID(), nullable=True),
    sa.Column('rule_id', sa.UUID(), nullable=True),
    sa.Column('listing_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rule_id'], ['watch_search_rules.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['watch_release_id'], ['watch_releases.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_events_type_created_at', 'events', ['type', 'created_at'], unique=False)
    op.create_index('ix_events_user_created_at', 'events', ['user_id', 'created_at'], unique=False)
    op.create_table('watch_matches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('rule_id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('matched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('match_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rule_id'], ['watch_search_rules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rule_id', 'listing_id', name='uq_match_rule_listing')
    )
    op.create_index('ix_watch_matches_rule_matched_at', 'watch_matches', ['rule_id', 'matched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_watch_matches_rule_matched_at', table_name='watch_matches')
    op.drop_table('watch_matches')
    op.drop_index('ix_events_user_created_at', table_name='events')
    op.drop_index('ix_events_type_created_at', table_name='events')
    op.drop_table('events')
    op.drop_index('ix_watch_search_rules_user_active', table_name='watch_search_rules')
    op.drop_index('ix_watch_search_rules_query_gin', table_name='watch_search_rules', postgresql_using='gin')
    op.drop_table('watch_search_rules')
    op.drop_index('ix_watch_releases_user_active', table_name='watch_releases')
    op.drop_table('watch_releases')
    op.drop_index('ix_price_snapshots_listing_recorded_at', table_name='price_snapshots')
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_provider_requests_status_code', table_name='provider_requests')
    op.drop_index('ix_provider_requests_provider_created_at', table_name='provider_requests')
    op.drop_table('provider_requests')
    op.drop_index('ix_listings_provider_status_last_seen', table_name='listings')
    op.drop_index(op.f('ix_listings_discogs_release_id'), table_name='listings')
    op.drop_table('listings')
    # ### end Alembic commands ###
