"""limit nulls normalized_title index

Revision ID: 52b7398d4aa3
Revises: 641f9a460f64
Create Date: 2026-02-20 00:33:06.891061

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "52b7398d4aa3"
down_revision: str | Sequence[str] | None = "641f9a460f64"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_listings_normalized_title_trgm", table_name="listings")

    op.create_index(
        "ix_listings_normalized_title_trgm",
        "listings",
        ["normalized_title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized_title": "gin_trgm_ops"},
        postgresql_where=sa.text("normalized_title IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_listings_normalized_title_trgm", table_name="listings")

    op.create_index(
        "ix_listings_normalized_title_trgm",
        "listings",
        ["normalized_title"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"normalized_title": "gin_trgm_ops"},
    )
    # ### end Alembic commands ###
