"""add trigram index to listings.normalized_title

Revision ID: 641f9a460f64
Revises: 409a6dd61e20
Create Date: 2026-02-20 00:23:32.879904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '641f9a460f64'
down_revision: Union[str, Sequence[str], None] = '409a6dd61e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm;")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_listings_normalized_title_trgm', 'listings', ['normalized_title'], unique=False, postgresql_using='gin', postgresql_ops={'normalized_title': 'gin_trgm_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_listings_normalized_title_trgm', table_name='listings')
    # ### end Alembic commands ###
